"""add collections table

Revision ID: 05c7ff807237
Revises: b7d227ac5335
Create Date: 2026-06-08 13:07:31.316410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05c7ff807237'
down_revision: Union[str, None] = 'b7d227ac5335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('couple_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('cover_photo_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['cover_photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photos', sa.Column('collection_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'photos', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'collection_id')
    op.drop_table('collections')
    # ### end Alembic commands ###
