"""add happened_at to transactions

Revision ID: 2a98e3c33885
Revises: cf7608ef89df
Create Date: 2026-06-08 16:30:13.581871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a98e3c33885'
down_revision: Union[str, None] = 'cf7608ef89df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('happened_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'happened_at')
    # ### end Alembic commands ###
