"""add photo and note to penalties

Revision ID: 4c1fa14ecf67
Revises: c5287adceee9
Create Date: 2026-06-08 17:57:48.482737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4c1fa14ecf67'
down_revision: Union[str, None] = 'c5287adceee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('funds', 'icon',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('penalties', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('penalties', sa.Column('note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('penalties', 'note')
    op.drop_column('penalties', 'photo_url')
    op.alter_column('funds', 'icon',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               existing_nullable=True)
    # ### end Alembic commands ###
