"""add generate_count to magazines

Revision ID: 4e32a14ed5b7
Revises: 4c1fa14ecf67
Create Date: 2026-06-08 19:34:20.784009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e32a14ed5b7'
down_revision: Union[str, None] = '4c1fa14ecf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('magazines', sa.Column('generate_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('magazines', 'generate_count')
    # ### end Alembic commands ###
