"""add magazines table

Revision ID: 51f52890ca1e
Revises: 549590cd664b
Create Date: 2026-05-29 22:28:45.631453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f52890ca1e'
down_revision: Union[str, None] = '549590cd664b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('magazines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('couple_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('month', sa.String(length=2), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('magazines')
    # ### end Alembic commands ###
