"""add content to moods

Revision ID: b9df5d818842
Revises: 4e32a14ed5b7
Create Date: 2026-06-08 20:53:29.537839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9df5d818842'
down_revision: Union[str, None] = '4e32a14ed5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moods', sa.Column('content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moods', 'content')
    # ### end Alembic commands ###
