"""add custom split to transactions

Revision ID: c5287adceee9
Revises: d41c2e730402
Create Date: 2026-06-08 17:30:24.526518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5287adceee9'
down_revision: Union[str, None] = 'd41c2e730402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('custom_amount', sa.Float(), nullable=True))
    # 更新 split_type 枚举，加入 custom
    op.execute("ALTER TABLE transactions MODIFY COLUMN split_type ENUM('equal','payer_full','other_full','custom','fund') DEFAULT 'equal'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'custom_amount')
    # ### end Alembic commands ###
