"""add type to fund_contributions

Revision ID: cf7608ef89df
Revises: 05c7ff807237
Create Date: 2026-06-08 15:51:58.545078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7608ef89df'
down_revision: Union[str, None] = '05c7ff807237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fund_contributions', sa.Column('type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_contributions', 'type')
    # ### end Alembic commands ###
