"""add funds transactions penalties tables

Revision ID: d31f4909d614
Revises: 51f52890ca1e
Create Date: 2026-05-29 22:47:54.310847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd31f4909d614'
down_revision: Union[str, None] = '51f52890ca1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('couple_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('couple_id', sa.String(length=36), nullable=False),
    sa.Column('issuer_id', sa.String(length=36), nullable=False),
    sa.Column('offender_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('penalty_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('is_done', sa.Boolean(), nullable=True),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['issuer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('couple_id', sa.String(length=36), nullable=False),
    sa.Column('paid_by', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('split_type', sa.Enum('equal', 'payer_full', 'other_full', 'fund', name='split_type_enum'), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['couple_id'], ['couples.id'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_contributions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fund_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fund_id'], ['funds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fund_contributions')
    op.drop_table('transactions')
    op.drop_table('penalties')
    op.drop_table('funds')
    # ### end Alembic commands ###
