"""add monthly_budget to couples

Revision ID: d41c2e730402
Revises: 2a98e3c33885
Create Date: 2026-06-08 16:59:10.847289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41c2e730402'
down_revision: Union[str, None] = '2a98e3c33885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couples', sa.Column('monthly_budget', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couples', 'monthly_budget')
    # ### end Alembic commands ###
