"""add created_at to wishes

Revision ID: d43329a7aba3
Revises: 3b6010a26d08
Create Date: 2026-06-19 13:32:46.733349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd43329a7aba3'
down_revision: Union[str, None] = '3b6010a26d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('magazines', 'generate_count',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('wishes', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishes', 'created_at')
    op.alter_column('magazines', 'generate_count',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
