"""update footprints table

Revision ID: e81bdc6b1249
Revises: d31f4909d614
Create Date: 2026-05-29 22:55:14.001910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e81bdc6b1249'
down_revision: Union[str, None] = 'd31f4909d614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('footprints', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('footprints', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('footprints', 'created_at')
    op.drop_column('footprints', 'note')
    # ### end Alembic commands ###
